### ISSUE TITLE
Extract Assets.dat from NOT A HERO

### ISSUE THREAD

**Issue by Starastel** [snickerbockers/fp-assets#3]
I need to extract data from assets.dat from NOT A HERO.
Thank you in advance!
Below are files from the Linux and Windows versions of the game.
[Windows Files](https://drive.google.com/file/d/1SiqAC05j9X7AnlXsPaWTxlYQzaUHdhST/view?usp=sharing)
[Linux Files](https://drive.google.com/file/d/1uEpLOWWoHVK6_tBM6O8bfEY7yYhMEmiD/view?usp=sharing)

**Comment by snickerbockers** [comment]
you need to figure it out by reverse-engineering the game's executable. When I did this for Freedom Planet, it was relatively easy because mp2 accidentally shipped debug symbols in the linux build. IDK if he still makes that mistake, but one other possible way to figure this out would be to use a tool like strace to record all the system calls it makes; since it needs the offset block to load the game's assets, it should have to seek there first before doing any reads.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Starastel** [comment]
Ok, i try it. Thanks.
